### ISSUE TITLE
请问如何得到推荐给每个用户前K个商品的id？

### ISSUE THREAD

**Issue by zhuty16** [Qcactus/CPR#4]
如题，谢谢~

**Comment by Qcactus** [comment]
这里没有专门的接口做这件事，可以加一些代码自行实现：

[这行](https://github.com/Qcactus/CPR/blob/782edb82ea8e996071807a9e5c5f9ef1c477e6ce/recq/recommenders/bpr.py#L258)之后的batch_ratings表示batch_u中每个user的推荐物品得分，batch_ratings[i][j]即对于用户batch_u[i]推荐item j的分数，可以用这个变量算一下topk (heapq.nlargest(...))

**Comment by zhuty16** [comment]
> 这里没有专门的接口做这件事，可以加一些代码自行实现：
> 
> [这行](https://github.com/Qcactus/CPR/blob/782edb82ea8e996071807a9e5c5f9ef1c477e6ce/recq/recommenders/bpr.py#L258)之后的batch_ratings表示batch_u中每个user的推荐物品得分，batch_ratings[i][j]即对于用户batch_u[i]推荐item j的分数，可以用这个变量算一下topk (heapq.nlargest(...))

所以CPR最终的推荐列表排序是根据tf.matmul(self.u_embeds, tf.transpose(self.i_embeds))对吗？

**Comment by Qcactus** [comment]
是的（再排除掉训练集中user已经交互过的item）

**Comment by zhuty16** [comment]
> 是的（再排除掉训练集中user已经交互过的item）

好的，谢谢
